### ISSUE TITLE
Add vector layer with the footprints of all products of a particular collection

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/evo-odas#206]
Now it's possible to extract the footprints of granules, but it's not the same thing (granule footprints are bboxes, product footprints can be, and normally are, generic polygons)

**Comment by aaime** [comment]
Note, this also needs to be automatically created/linked when creating a collection layer.

**Comment by randomorder** [comment]
- [ ] Add support in GeoServer #238 
- [ ] Improve S1 DAG to extract S1 footprint #235 
- [ ] Improve S2 DAG to extract S2 footprint #236 
- [ ] Improve L8 DAG to extract L8 footprint #237
