### ISSUE TITLE
Import Landsat-8 products

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/evo-odas#59]
Initial breakdown.

- [x] #93 gdal_translate operator
- [x] #94 Enhance gdalAddo operator
- [x] #95 Create thumbnails operator
- [ ] #96 Create quicklook operator
- [x] #97 meta-data operator

**Comment by randomorder** [comment]
Quicklook not yet supported
Currently ingesting only 1 band. Multiband support in progress #127
